@startuml Kimifeel

hide empty members

class Endpoints

package Clients #DDDDFF {
    together {
        class WebAPI
        class DiscordClient
    }
    WebAPI -> Endpoints
    DiscordClient -> Endpoints
    WebAPI -[hidden]- DiscordClient
}

Controllers --> Endpoints
Controllers --> Models
Models --> Firestore

@enduml
