version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: kimifeel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kimifeel
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"

  migration:
    build:
      context: .
      dockerfile: migration.Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started

  server:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
